// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyvizuDP1KZ-zVqSx0v4TvkFx6yIrqxg',
    appId: '1:666416714876:web:bae037f6d2e9dde66a65f9',
    messagingSenderId: '666416714876',
    projectId: 'ljhy-flutter',
    authDomain: 'ljhy-flutter.firebaseapp.com',
    storageBucket: 'ljhy-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2MsSFttsga2E1lgyspOdi3SLwC2Xn2U',
    appId: '1:666416714876:android:15cdfb267a51faaa6a65f9',
    messagingSenderId: '666416714876',
    projectId: 'ljhy-flutter',
    storageBucket: 'ljhy-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXFYJip9UkGDHqpdDnR0xk3pIfwJR7Zc',
    appId: '1:666416714876:ios:8e98cbeda2b864e56a65f9',
    messagingSenderId: '666416714876',
    projectId: 'ljhy-flutter',
    storageBucket: 'ljhy-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterClassBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXFYJip9UkGDHqpdDnR0xk3pIfwJR7Zc',
    appId: '1:666416714876:ios:8e98cbeda2b864e56a65f9',
    messagingSenderId: '666416714876',
    projectId: 'ljhy-flutter',
    storageBucket: 'ljhy-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterClassBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByyvizuDP1KZ-zVqSx0v4TvkFx6yIrqxg',
    appId: '1:666416714876:web:7ffd130fca4087ff6a65f9',
    messagingSenderId: '666416714876',
    projectId: 'ljhy-flutter',
    authDomain: 'ljhy-flutter.firebaseapp.com',
    storageBucket: 'ljhy-flutter.firebasestorage.app',
  );

}